import os
import toml

from nycschools import config
from invoke import task


def get_project_config():
    config = {}
    with open('pyproject.toml', 'r') as f:
        config = toml.load(f)
    return config["project"]

@task
def archive(c):
    """Create a .7z archive of all of the files in the data directory."""
    
    print("Creating a .7z archive of all of the files in the data directory.")

    data_dir = os.path.abspath(config.  data_dir)
    filename = config.urls["school-data-archive"].filename
    print("removing existing archive", filename)
    c.run(f"rm -f {filename}")
    print(f"creating archive {filename} from {data_dir}/*")
    c.run(f"7z a {filename} {data_dir}/*")

@task 
def clean(c):
    """Remove dist and docs directories."""
    c.run("rm -rf dist")
    c.run("rm -rf docs")

@task
def build(c):
    """Build the package."""
    project = get_project_config()
    print(f"building {project['name']} v{project['version']} ")
    c.run("rm -rf dist")
    c.run("python -m build")
    c.run(f"cp dist/nycschools-{project['version']}.tar.gz dist/nycschools-latest.tar.gz")

@task
def push(c, production=False):
    """Push the current distribution to pypi.
    By default, this pushes to testpypi.
    To push to pypi, use the -p or --production flag.
    """
    project = get_project_config()
    current = f"nycschools-{project['version']}"
    if production:
        print("Pushing to pypi. This is NOT A DRILL.")
        c.run(f"twine upload dist/{current}*")
    else:
        print("Pushing to testpypi")
        c.run(f"twine upload --repository testpypi dist/{current}*")
    

@task
def test(c, opt=""):
    """Run unit tests."""
    c.run(f"pytest {opt}")

@task
def docs(c, clean=False):
    """Build the documentation with sphynx."""
    if clean:
        c.run("rm -rf docs")
    c.run("sphinx-apidoc nycschools -o docs-source/api")
    c.run("sphinx-build -j 4 -b html docs-source docs")
    c.run("touch docs/.nojekyll")

@task
def toc(c):
    """Generate table of content files for each
    folder in docs-source/nb."""
    def write_toc(file, toc, caption=""):
        if os.path.exists(file):
            os.remove(file)
        with open(file, "w") as f:
            f.write(f"""<!-- This file is automatically generated by tasks.py -->
```{{toctree}}
---
caption: {caption}
maxdepth: 2
numbered:
---
{toc}
```
""" )

    for root, dirs, files in os.walk("docs-source/nb"):
        if root == "docs-source/nb":
            toc = [f"nb/{d}/index.md" for d in dirs if d[0] not in [".", "_"]]
            toc = sorted(toc)
            toc = "\n".join(toc)
            f = os.path.join(root, f"toc.md")
            write_toc(f, toc, "Guides")
        else:
            sub = root.split("/")[-1]
            toc = [f"{f}" for f in files if f.endswith(".ipynb")]
            toc = sorted(toc)
            toc = "\n".join(toc)
            f = os.path.join(root, "toc.md")
            write_toc(f, toc, sub)

@task
def install_from_testpypi(c):
    """Install the package from testpypi but using real pypi for dependencies."""
    c.run("python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple nycschools")


@task
def tag(c):
    """Tag the current version."""
    project = get_project_config()
    version = project["version"]
    c.run(f"git tag -a {version} -m 'version {version}'")
    c.run(f"git push --tags")