# -*- coding: utf-8 -*-
"""examples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/159Lbz4oah1IFa1N_KodPaRBJ6dzpnjzi
"""

#contain all examples from the nyc open data project notebooks

from IPython.display import HTML

import inspect
import builtins

# example 1 from loading data notebook
def hidden_code1():
    # This is the solution
    df.head(10)

# Define the HTML for the spoiler button
spoiler_button1 = '''
<button onclick="if(document.getElementById('spoiler').style.display=='none') {document.getElementById('spoiler').style.display=''} else {document.getElementById('spoiler').style.display='none'}">Show Code</button>
'''

# Get the source code of the function as a string
source_code1 = inspect.getsource(hidden_code1)

# Remove the first line of the source code (the function definition)
source_code1 = '\n'.join(source_code1.split('\n')[2:])

# Define the HTML for the code block that will be revealed (without the function name)
spoiler_content1 = '''
<div id="spoiler" style="display:none">
<pre><code>{}</code></pre>
</div>
'''.format(source_code1)

# Combine the spoiler button and content HTML into a single string
solution1 = spoiler_button1 + spoiler_content1

# Display the spoiler code as HTML
HTML(solution1)

# example 2 from loading data notebook
def hidden_code2():
    # This is the solution
    swd = df["swd_pct"]
    swd.mean()


# Define the HTML for the spoiler button
spoiler_button2 = '''
<button onclick="if(document.getElementById('spoiler1').style.display=='none') {document.getElementById('spoiler1').style.display=''} else {document.getElementById('spoiler1').style.display='none'}">Show Code</button>
'''

# Get the source code of the function as a string
source_code2 = inspect.getsource(hidden_code2)

# Remove the first line of the source code (the function definition)
source_code2 = '\n'.join(source_code2.split('\n')[2:])

# Define the HTML for the code block that will be revealed (without the function name)
spoiler_content2 = '''
<div id="spoiler1" style="display:none">
<pre><code>{}</code></pre>
</div>
'''.format(source_code2)

# Combine the spoiler button and content HTML into a single string
solution2 = spoiler_button2 + spoiler_content2

# Display the spoiler code as HTML
HTML(solution2)